### ISSUE TITLE
is possible to skip the adapter trimming?

### ISSUE THREAD

**Issue by lpantano** [friedlanderlab/mirtrace#2]
Hi,

thanks for the awesome tool :)

I am adapting this tool to some pipelines, it is possible to skip the adapter trimming step, for instance, if you want to re-analyze the data and it comes already trimmed?

Thanks!

**Comment by yrin** [comment]
Hi,
It should be possible to simply not specify an adapter and thus bypassing trimming.
Please let me know if there are any issues with this.

Sorry for the late reply. 

Best,

**Comment by lpantano** [comment]
Hi,

Thanks! I will try that then, but happens with `protocol` option, by default is illumina, and if I don't specify adapter it would try to set up the adapter? 

I can play around, but if you have a specific command that would work, I would take it :)

Cheers

**Comment by wenjingk** [comment]
Hi,

the default nucleotides for adapter trimming (-a option) is none. If you don't specify adapter it will bypass the trimming. 

An example command could be: mirtrace qc -s species_of_your_sample input.fastq. If you need the QC-passed and collapsed reads in fasta format to the output folder, use -w option. 

Let me know if anything is unclear. : )

Cheers

**Comment by lpantano** [comment]
cool, this is working! thanks a lot!
