### ISSUE TITLE
Is it possible to provide mirbase files via command line instead of just using the hardcoded one of mirbase 21

### ISSUE THREAD

**Issue by shashwatsahay** [friedlanderlab/mirtrace#3]

**Comment by wenjingk** [comment]
Hi!

unfortunately, the current version does not support that. You are right, you cannot change the hardcoded miRBase database. 

Cheers,
Wenjing

**Comment by wenjingk** [comment]
Hi! 

again, I forget to mention you can use custom miRNA, tRNA and rRNA reference database for mapping, which is related to the RNA type plot of miRTrace report. You can find more information in the mirtrace manual. If you have further question, let me know. :)

https://github.com/friedlanderlab/mirtrace/blob/master/release-bundle-includes/doc/manual/mirtrace_manual.pdf

Cheers,
Wenjing

**Comment by shashwatsahay** [comment]
Hi!

Looks like this should solve my problem. Thanks :)

Regards
Shashwat
